php/controllers/ServerLoadController.php
<?php

declare (strict_types=1);

namespace app\controllers;

use app\models\server\LoadRecord;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\web\Response;

class ServerLoadController extends BaseController
{

    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    // allow only POST requests
                    [
                        'allow' => true,
                        'verbs' => ['POST'],
                        'roles' => ['@']
                    ],
                ],
            ],
        ];
    }

    public function actions(): array
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     *
     * @param string $id
     * @param array $params
     * @return mixed
     * @throws \yii\base\InvalidRouteException
     */
    public function runAction($id, $params = [])
    {
        if ($id === 'get') {
            $params = yii\helpers\ArrayHelper::merge(Yii::$app->request->post(), $params);
        }
        return parent::runAction($id, $params);
    }

    /**
     *
     * @param string $date
     * @param string $type
     * @param int $limit
     * @return string
     */
    public function actionGet(string $date, string $type, int $limit = 19): string
    {
        if ($date === 'now') {
            $date = date_create('now', new \DateTimeZone(\Yii::$app->timeZone))->format('Y-m-d H:i:s');
        }
        $data = LoadRecord::findByDateAndType($date, $type, $limit);
        return json_encode($data);
    }

}

php/controllers/SiteController.php
<?php

declare(strict_types=1);

namespace app\controllers;

use app\models\auth\User;
use app\models\Notification;
use app\models\NotificationSearch;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use yii\web\Response;
use app\widgets\charts\AreaChart;
use app\models\helpers\AreaChartOptionsBuilder;
use yii\web\JsExpression;
use app\widgets\charts\Dataset as ChartDataset;

class SiteController extends BaseController
{
    public function behaviors() : array
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions() : array
    {
        return [
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function beforeAction($action)
    {
        if ($action->id === 'login') {
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action);
    }

    public function actionIndex() : string
    {
        //$tmp = shell_exec("/home/test/p0f-mtu/p0f-client /home/test/p0f-socket {$_SERVER['REMOTE_ADDR']}");
        /**
         * @var User $user
         */
        $user = Yii::$app->user->getIdentity();
        if ($user === null) {
            return $this->render('index-guest');
        }

        if ($user->isAdmin())
        {
            return $this->renderAdminIndex();
        }

        return $this->render('index-user');
    }

    private function getRadarData() : array
    {
        $nSearch = new NotificationSearch();
        $taskIds = [
            [
                'id' => 16,
                'name' => 'My Cloud',
                'color' => '#8bc34a',
            ],
            [
                'id' => 17,
                'name' => 'Test WP site',
                'color' => '#2196f3',
            ],
            [
                'id' => 19,
                'name' => 'Test task 10',
                'color' => '#c7954a',
            ],
        ];
        $levels = Notification::getLevelsAsArray();
        $max = 0;
        $datasets = [];
        foreach ($taskIds as $arr) {
            $levelsCount['data'] = $nSearch->getNotificationsCount([$arr['id']], ['level'], false);
            $levelsCount['label'] = $arr['name'];
            $levelsCount['borderColor'] = $arr['color'];

            $levelsCount['data']['Unknown'] = rand(0, 10);
            foreach ($levels as $level) {
                if (!array_key_exists($level, $levelsCount)) {
                    $levelsCount[$level] = 0;
                } else if ($levelsCount[$level] > $max) {
                    $max = $levelsCount[$level];
                }
            }
            $levelsCount['data'] = array_values($levelsCount['data']);
            $datasets[] = $levelsCount;
        }
        return [
            'labels' => $levels,
            'datasets' => $datasets,
            'max' => $max,
        ];
    }

    private function renderAdminIndex() : string
    {
        $b = new AreaChartOptionsBuilder();
        $b->setTooltipLabelCallback(new JsExpression(AreaChartOptionsBuilder::DEFAULT_TOOLTIP_LABEL_CALLBACK));
        $b->setYAxesValueFormat(new JsExpression(AreaChartOptionsBuilder::DEFAULT_Y_AXES_FORMAT));
        $areaChart = new AreaChart();
        $areaChart->setHeader('Notifications summary');
        $areaChart->setOptionsBuilder($b);
        $dateNow = new \DateTime();
        $nData = NotificationSearch::find()
            ->select(['count(*) as c', 'level', 'creation_date', 'datediff(now(), creation_date) as dd'])
            ->where(['<=', 'creation_date', $dateNow->format('Y-m-d H:i:s')])
            ->andWhere(['>=', 'creation_date', $dateNow->sub(new \DateInterval('P1M'))->format('Y-m-d H:i:s')])
            ->groupBy(['dd', 'level'])
            ->orderBy(['creation_date' => 'ASC'])
            ->asArray()
            ->all();
        $chartDatasets = [];
        $dates = [];
        foreach ($nData as $el) {
            $ymdStr = mb_substr($el['creation_date'], 0, mb_strpos($el['creation_date'], ' '));
            $dates[] = $ymdStr;
            $level = $el['level'];
            if (!array_key_exists($level, $chartDatasets)) {
                $chartDatasets[$level] = [];
            }
            $chartDatasets[$level][] = intval($el['c']);
        }
        $areaChart->setLabels($dates);
        $tmp = [];
        foreach ($chartDatasets as $k => $v) {
            $tmp[$k] = (new ChartDataset('label_'.$k))->setData($v);
        }
        $areaChart->updateDatasets([
            (new ChartDataset('label1'))->setData([1, 4, 5, 10, 44, 30, 12, 22, 12, 10, 2, 5]),
            (new ChartDataset('label2'))->setData([0, 2, 4, 1, 3, 3, 2, 2, 5, 8, 2, 1]),
        ]);
        return $this->render(
            'index-admin',
            [
                'areaChart' => $areaChart,
                'radarData' => $this->getRadarData()
            ]
        );
    }

    public function actionLogin() : Response
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        $response = new Response();
        $response->content = $this->renderPartial('login', [
            'model' => $model,
        ]);
        return $response;
    }

    public function actionLogout() : Response
    {    
        $sessionAdminId = \Yii::$app->getSession()->get(User::ADMIN_ID_SESSION_KEY);
        Yii::$app->user->logout();       
        if (intval($sessionAdminId) > 0)
        {
            $model = new LoginForm();
            if (!$model->loginAs($sessionAdminId))
            {
                \Yii::error(__METHOD__.": не удалось вернуться в сессию админа после выхода из пользователя.");
            }
            else
            {
                \Yii::$app->getSession()->set(User::ADMIN_ID_SESSION_KEY, null);
            }
        }

        return $this->goHome();
    }

    public function actionAbout() : string
    {
        return $this->render('about');
    }
    
    public function actionInfo() : string
    {
        return $this->render('info');
    }

    public function actionError()
    {
        $exception = Yii::$app->errorHandler->exception;
        $this->layout = 'sbadmin';
        if ($exception instanceof \Exception)
        {
            return $this->render('error', ['exception' => $exception]);
        }
        return $this->goHome();
    }
}

php/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use kartik\markdown\Markdown;
use app\assets\SiteAboutAsset;

SiteAboutAsset::register($this);

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>
    <?= Markdown::convert(file_get_contents(Yii::$app->getBasePath().'/assets/md/readme.md')); ?>
</div>
<div class="site-about">
    <div id="bpmn"></div>
</div>

php/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

php/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;
$urlManager = \Yii::$app->getUrlManager();
$identity = Yii::$app->user->getIdentity();

$this->title = $name;
?>
<div class="text-center">
    <div class="error mx-auto" data-text="<?= Html::encode($exception->statusCode ); ?>"><?= Html::encode($exception->statusCode ); ?></div>
    <p class="lead text-gray-800 mb-5">Page Not Found</p>
    <p class="text-gray-500 mb-0">It looks like you found a glitch in the matrix...</p>
    <?php if ($identity instanceof \app\models\auth\User): ?>
        <a href="<?= $urlManager->createUrl('site/index') ?>">&larr; Back to Dashboard</a>
    <?php else: ?>
        <a href="<?= $urlManager->createUrl('site/login') ?>">&larr; Please login to view dashboard</a>
    <?php endif; ?>
</div>

php/views/site/index-admin.php
<?php

use app\models\runners\CliRunnerSettings;
use yii\data\ArrayDataProvider;
use app\widgets\charts\AreaChart;

$command = new \app\models\commands\PsCommand();
$command->setRunnerSettings(new CliRunnerSettings());
//$command->run();
$provider = new ArrayDataProvider([
        //$command->getRunningProcesses()
    'allModels' => [],
    'sort' => [
        //'attributes' => ['id', 'username', 'email'],
    ],
    'pagination' => [
        'pageSize' => 30,
    ],
]);

/* @var $this yii\web\View */
/* @var $areaChart AreaChart */
/* @var $radarData array */

$this->title = '';
?>
<script src="/js/Chart.min.js"></script>
<div class="site-index">

    <div class="body-content">
        <div class="row">
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-warning shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                    Sent alerts</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">14</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-comments fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <h2 style="text-align: center">Notifications by user task</h2>
        <div class="row">
            <canvas id="radar"></canvas>
        </div>
    </div>
</div>
<script>
    
    /**
     * 
     * @param {string} date
     * @param {string} type
     * @param {integer} limit
     * @param {function} callback
     * @returns {undefined}
     */
    function getServerLoadData(series, date, type, limit, callback)
    {
        return;
        $.ajax({
            url: '<?= \Yii::$app->getUrlManager()->createUrl('server-load/get') ?>',
            type: 'POST',
            dataType: 'json',
            data: {
                date: 'now', 
                type: type, 
                limit: limit,
                'csrf-param': typeof variable !== 'yii' ? yii.getCsrfParam() : '',
                'csrf-token': typeof variable !== 'yii' ? yii.getCsrfToken() : ''
            },
            success: function (data) {
                //console.log('success', data[0]);
                callback(data);
            }
        });
    }
    const ctx = document.getElementById("radar");
    const options = {
        scale: {
            angleLines: {
                display: true
            },
            ticks: {
                suggestedMin: 1,
                suggestedMax: <?= intval($radarData['max']) ?>
            }
        }
    };
    const data = {
        labels: <?= json_encode($radarData['labels']); ?>,
        datasets: <?= json_encode($radarData['datasets']); ?>
    }
    const myRadarChart = new Chart(ctx, {
        type: 'radar',
        data: data,
        options: options
    });
</script>

php/views/site/index-guest.php
<?php
declare(strict_types=1);

use yii\helpers\Html;

/* @var $this yii\web\View */

$this->title = '';
$urlManager = \Yii::$app->getUrlManager();
?>
<style>
    .sticky-footer {
        position: fixed;
        width: 100%;
        bottom: 0;
    }
</style>
<div class="site-index">

    <div class="jumbotron">
        <h1>Guest index page</h1>
        <?php if (Yii::$app->params['isDemo'] !== 0): ?>
            <h2>This is a demo environment</h2>
            <h3>Use <?= Html::encode(getenv('YPA_DEMO_USERNAME').':'.getenv('YPA_DEMO_PASSWORD')) ?> to login</h3>
        <?php endif; ?>

        <p><a class="btn btn-lg btn-success" href="<?= $urlManager->createUrl('site/login'); ?>">Login</a></p>
    </div>

    <!--<div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2></h2>
                <p></p>
            </div>
            <div class="col-lg-4">
                <h2></h2>
                <p></p>
            </div>
            <div class="col-lg-4">
                <h2></h2>
                <p></p>
            </div>
        </div>

    </div>-->
</div>

php/views/site/index-user.php
<?php

/* @var $this yii\web\View */

$this->title = '';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>User index</h1>
    </div>

    <div class="body-content">

    </div>
</div>

php/views/site/info.php
<?php

phpinfo();

php/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\assets\SbAppAsset;

SbAppAsset::register($this);

?>
<?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body class="bg-gradient-primary">
    <?php $this->beginBody() ?>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-5 col-lg-6 col-md-9">
                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <div class="">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                </div>
                                <?php $form = ActiveForm::begin([
                                    'id' => 'login-form',
                                    'options' => [
                                        'class' => 'user',
                                    ],
                                    'fieldConfig' => [
                                        'template' => "<div class=\"form-group\">{input}</div>",

                                    ],
                                ]); ?>
                                <?= $form->field($model, 'username')->textInput([
                                    'autofocus' => true,
                                    'class' => 'form-control form-control-user',
                                    'aria-describedby' => '',
                                    'placeholder' => 'Enter username...',
                                ]) ?>
                                <?= $form->field($model, 'password')->passwordInput([
                                    'autofocus' => true,
                                    'class' => 'form-control form-control-user',
                                    'aria-describedby' => '',
                                    'placeholder' => 'Password',
                                ]) ?>
                                <?= $form->field($model, 'rememberMe')->checkbox([
                                    'class' => 'custom-control-input',
                                    'template' => "<div class=\"custom-control custom-checkbox small\">{input}{label}{error}</div>",
                                ])->label('Remember Me', ['class' => 'custom-control-label']) ?>
                                <?= Html::submitButton('Login', ['class' => 'btn btn-primary btn-user btn-block', 'name' => 'login-button']) ?>
                                <hr>
                                <?php ActiveForm::end(); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php $this->endBody() ?>
    </body>
    </html>
<?php $this->endPage() ?>

php/views/site/test.php
<?php

use app\widgets\notification\Notification;
use \app\widgets\card\BigCard;
use yii\helpers\Html;

$this->title = '1234';

?>
<div class="row">

    <?= \app\widgets\card\Card::widget([
        'icon' => 'fa-calendar',
        'text' => '86%',
        'header' => 'Tasks',
        'cardType' => \app\widgets\card\Card::TYPE_SUCCESS,
        'progressBar' => new \app\widgets\progressbar\ProgressBar(['value' => 86]),
    ]); ?>
</div>

<div class="row">
    <?= BigCard::widget([
        'className' => BigCard::CLASS_GRAPHIC_LONG,
        'text' => 'TestText',
        'header' => 'Header',
    ])
    ?>
</div>

<!-- Content Row -->
<div class="row">
    <!-- Content Column -->
    <div class="col-lg-6 mb-4">
        <div class="row">
            <?= Notification::widget([
                    'bgColor' => Notification::COLOR_DARK, 
                    'caption' => 'Test',
                    'text' => 'text',
                ]);
            ?>        
        </div>
    </div>
</div>