php/controllers/NotificationController.php
<?php

declare(strict_types=1);

namespace app\controllers;

use app\exceptions\ValueError;
use app\models\helpers\DemoRulesHelper;
use Yii;
use app\models\Notification;
use app\models\NotificationSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\auth\User;
use yii\filters\AccessControl;

/**
 * NotificationController implements the CRUD actions for Notification model.
 */
class NotificationController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors() : array
    {
        $availActions = ['index', 'view', ];
        $nonDemoActions = ['take', 'free', 'general'];
        $rulesHelper = new DemoRulesHelper($availActions, $nonDemoActions);
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => $rulesHelper->getAllActions(),
                'rules' => $rulesHelper->getRules(),
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    //'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Notification models.
     * @return mixed
     */
    public function actionIndex() : string
    {
        $searchModel = new NotificationSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Notification model.
     * @param integer $id
     * @return mixed
     */
    public function actionView(int $id) : string
    {
        $model = $this->findModel($id);
        $task = $model->getTask()->one();       
        $userId = User::getCurrentUserId();
        
        if ($model->taken_by_user_id !== $userId && $task->user_id !== $userId)
        {
            throw new ValueError('Can not get access to record');
        }
        
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Finds the Notification model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Notification the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel(int $id) : Notification
    {
        if (($model = Notification::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    /**
     * 
     * @param int $id
     * @return string
     * @throws \LogicException
     */
    public function actionTake(int $id) 
    {
        try
        {
            $model = $this->findModel($id);
            $user = User::getCurrentUser();
            
            //Если уже взято - редиректим
            if ($model->taken_by_user_id === $user->id)
            {
                return $this->redirect(['view', 'id' => $id]);
            }
            
            if ($user->isAdmin())
            {
                throw new \LogicException('User is admin');
            }
            if (!$model->isCreatedByAdmin())
            {
                throw new \LogicException('Motification is not created by admin task');
            }

            $model->taken_by_user_id = $user->id;
            if (!$model->validate())
            {
                throw new \LogicException('Model->validate() error');
            } 
            $model->save();
            return $this->redirect(['view', 'id' => $id]);
        } catch (\Exception $ex) {
            \Yii::error(__METHOD__.": ".$ex->getMessage());
            return $this->redirect(['general']);
        }          
    }
    
    /**
     * 
     * @param integer $id
     * @return type
     */
    public function actionFree(int $id)
    {
        try
        {
            $user = User::getCurrentUser();
            if ($user->isAdmin())
            {
                throw new \LogicException('User is admin');
            }
            
            $model = $this->findModel($id);
            if ($model->taken_by_user_id !== User::getCurrentUserId())
            {
                return $this->redirect(['index']);
            }
            
            $model->taken_by_user_id = null;
            $model->save();
                    
        } catch (\Exception $ex) {
            \Yii::error(__METHOD__.": ".$ex->getMessage());
        }
        return $this->redirect(['general']);
    }
    
    /**
     * Страница уведомлений, которые были созданы от задач администраторов
     * @return string
     */
    public function actionGeneral() : string
    {
        $searchModel = new NotificationSearch();
        $dataProvider = $searchModel->searchCreatedByAdmin(Yii::$app->request->queryParams);

        return $this->render('general', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
}

php/controllers/TaskController.php
<?php

declare(strict_types=1);

namespace app\controllers;

use app\exceptions\ValueError;
use app\models\helpers\DemoRulesHelper;
use app\models\Notification;
use app\models\NotificationSearch;
use app\widgets\card\Card;
use app\widgets\progressbar\ProgressBar;
use Yii;
use app\models\Task;
use app\models\TaskSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use app\models\auth\User;
use yii\filters\AccessControl;
use yii\web\UploadedFile;
use app\widgets\charts\DonutDataset;
use app\widgets\charts\DonutChart;
use app\models\helpers\PieChartOptionsBuilder;

/**
 * TaskController implements the CRUD actions for Task model.
 */
class TaskController extends BaseController
{
    /**
     *
     * @var string 
     */
    protected static $nonAdminMesage = 'текущий пользователь не является администратором';

    /**
     * @inheritdoc
     */
    public function behaviors() : array
    {
        $availActions = ['index', 'view', ];
        $nonDemoActions = ['create', 'update', 'approve', 'push',];
        $rulesHelper = new DemoRulesHelper($availActions, $nonDemoActions);
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => $rulesHelper->getAllActions(),
                'rules' => $rulesHelper->getRules(),
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    //'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Task models.
     * @return mixed
     */
    public function actionIndex() : string
    {
        $searchModel = new TaskSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Task model.
     * @param integer $id
     * @return mixed
     */
    public function actionView(int $id) : string
    {
        $model = $this->findModel($id);
        $chart = new DonutChart();
        $chart->setHeader('Notifications by type');
        $nSearch = new NotificationSearch();
        $nData = $nSearch->getNotificationsCount([$model->id], ['level'], false);
        $colors = $this->getDonutColorsByNotificationLevel($nData);
        $chart->setLabels(array_keys($nData));
        $chart->setOptionsBuilder(new PieChartOptionsBuilder());
        $chart->updateDatasets([
            (new DonutDataset())
                ->setData(array_values($nData))
                ->setBackgroundColors($colors)
                ->setHoverBackground($colors)

        ]);
        $cardProgress = new Card();
        //todo: move to controller, get info from db
        $cardProgress->cardType = Card::TYPE_INFO;
        $cardProgress->header = 'Task progress';
        $cardProgress->text = '36%';
        $cardProgress->progressBar = new ProgressBar();
        $cardProgress->progressBar->type = ProgressBar::TYPE_INFO;
        $cardProgress->progressBar->value = 36;
        return $this->render('view', [
            'model' => $model,
            'domains' => $model->readDomains(),
            'domainsCount' => 0,
            'chart' => $chart,
            'cardProgress' => $cardProgress,
        ]);
    }

    /**
     * Возврат набора цветов для найденных уведомлений
     * @param array $nData
     * @return array
     */
    private function getDonutColorsByNotificationLevel(array $nData): array
    {
        $result = [];
        $colors = [
            DonutDataset::COLOR_NOTIFICATION_UNKNOWN,
            DonutDataset::COLOR_NOTIFICATION_LOW,
            DonutDataset::COLOR_NOTIFICATION_MEDIUM,
            DonutDataset::COLOR_NOTIFICATION_HIGH,
            DonutDataset::COLOR_NOTIFICATION_CRITICAL
        ];
        $nLevels = Notification::getLevelsAsArray();
        for ($i = 0; $i < count($nLevels); $i++) {
            if (array_key_exists($nLevels[$i], $nData)) {
                $result[] = $colors[$i];
            }
        }
        return $result;
    }

    /**
     * Creates a new Task model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     * @throws \Exception
     */
    public function actionCreate()
    {
        $model = new Task();

        if ($model->load(Yii::$app->request->post())) {
            $model->status = Task::STATUS_CREATED;
            $tmpDomainsFile = UploadedFile::getInstance($model, 'domains');
            if ($tmpDomainsFile !== null) {
                $model->filename = $model->uploadFile($tmpDomainsFile);
            }
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                //'domains' => $model->readDomains(),
            ]);
        }
    }

    /**
     *
     * @param int $id
     * @return mixed
     * @throws \Exception
     */
    public function actionApprove(int $id)
    {
        if (!User::currentUserIsAdmin())
        {
            \Yii::error(__METHOD__.": ".self::$nonAdminMesage);
            return $this->redirect(['view', 'id' => $id]);
        }
        Task::updateAll(['status' => Task::STATUS_APPROVED], ['=', 'id', $id]);
        return $this->redirect(['view', 'id' => $id]);
    }
    
    /**
     * 
     * @param integer $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionPush(int $id) : string
    {
        $model = $this->findModel($id);
        if (!User::currentUserIsAdmin())
        {
            \Yii::error(__METHOD__.": ".self::$nonAdminMesage);
            return $this->redirect(['view', 'id' => $model->id]);
        }
        
        if ($model->status !== Task::STATUS_APPROVED)
        {
            throw new ValueError('Task must be in "approved" status');
        }
        if (!$model)
        {
            throw new NotFoundHttpException('Not found task with id '.$id);
        }
        
        $domainsCount = $model->pushToQueue('task');
        return $this->render('view', [
            'model' => $model,
            'domains' => $model->readDomains(),
            'domainsCount' => $domainsCount,
        ]);      
    }

    /**
     * Finds the Task model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Task the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel(int $id) : Task
    {
        if (($model = Task::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

php/controllers/UserController.php
<?php

declare(strict_types=1);

namespace app\controllers;

use Yii;
use app\models\auth\User;
use app\models\auth\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use app\models\LoginForm;
use app\models\auth\AccessControlAdminOnly;

class UserController extends BaseController {
    
    /**
     * @inheritdoc
     */
    public function behaviors() : array
    {
        return [
            'access' => [
                'class' => AccessControlAdminOnly::className(),
                'only' => ['index', 'update', 'disable', 'set-as-admin', 'create', 'login-as'],
                'rules' => [
                    [
                        'actions' => ['index', 'update', 'disable', 'set-as-admin', 'create', 'login-as'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['GET'],
                    'disable' => ['GET'],
                    'set-as-admin' => ['GET'],
                ],
            ],
        ];
    }
    
    /**
     * Lists all Task models.
     * @return mixed
     */
    public function actionIndex() : string
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
    /**
     * Finds the Task model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel(int $id) : User
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return Response
     * @throws NotFoundHttpException
     */
    public function actionUpdate(int $id) : Response
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                //'domains' => $model->readDomains(),
            ]);
        }
    }
    
    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
    
    public function actionDisable(int $id, bool $disabled): string
    {
        User::updateAll(['disabled' => $disabled], 'id = '.$id);         
        return $this->actionIndex();
    }
    
    public function actionSetAsAdmin(int $id, bool $isAdmin): string
    {
        User::updateAll(['is_admin' => $isAdmin], 'id = '.$id);        
        return $this->actionIndex();
    }
    
    public function actionLoginAs(int $id)
    {
        /**
         * @var User $user
         */
        $user = Yii::$app->user->getIdentity();
        if ($user === null) {
            return $this->redirect(['site/index']);
        }

        \Yii::$app->getSession()->set(User::LOGIN_AS_SESSION_KEY, $id);
        \Yii::$app->getSession()->set(User::ADMIN_ID_SESSION_KEY, $user->id);
        $model = new LoginForm();
        $model->loginAs($id);
        return $this->goHome();        
    }
}

php/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $identity = Yii::$app->user->getIdentity();
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Main', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            //['label' => 'Contact', 'url' => ['/site/contact']],
            ['label' => 'Task data', 'url' => ['/task/index']],
            ['label' => 'Notifications', 'url' => ['/notification/index']],
            $identity !== null && $identity->isAdmin() ? (
                ['label' => 'Users', 'url' => ['/user/index']]
            ) : (''),
            $identity !== null && !$identity->isAdmin() ? (
                ['label' => 'General notifications', 'url' => ['/notification/general']]
            ) : (''),
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post', ['class' => 'navbar-form'])
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->name . ')',
                    ['class' => 'btn btn-link']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

php/views/layouts/sbadmin.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\SbAppAsset;

SbAppAsset::register($this);
$urlManager = \Yii::$app->getUrlManager();
/**
 * @var $identity \app\models\auth\User
 */
$identity = Yii::$app->user->getIdentity();
$loggedIn = $identity instanceof \app\models\auth\User;
$isAdmin = $loggedIn && $identity->isAdmin();
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div id="wrapper">

    <?php if ($loggedIn) : ?>
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<?= \Yii::$app->getHomeUrl(); ?>">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-paw"></i>
                </div>
                <div class="sidebar-brand-text mx-3">FAUNA</div>
            </a>
            <!-- Divider -->
            <hr class="sidebar-divider my-0">
            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="<?= \Yii::$app->getHomeUrl(); ?>">
                    <i class="fas fa-home"></i>
                    <span>Home</span></a>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider">
            <!-- Heading -->
            <div class="sidebar-heading">
                Information
            </div>
            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="<?= $urlManager->createUrl('task/index'); ?>">
                    <i class="fas fa-tasks"></i>
                    <span>Tasks</span></a>
            </li>
            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-envelope"></i>
                    <span>Notifications</span>
                </a>
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <!--<h6 class="collapse-header"></h6>-->
                        <a class="collapse-item" href="<?= $urlManager->createUrl('notification/index'); ?>">All</a>
                        <a class="collapse-item" href="<?= $urlManager->createUrl('notification/general'); ?>">General</a>
                    </div>
                </div>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider">
            <!-- Heading -->
            <div class="sidebar-heading">
                Rest
            </div>
            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link" href="<?= $urlManager->createUrl('site/about'); ?>">
                    <i class="fas fa-question"></i>
                    <span>About</span></a>
                <?php if ($isAdmin) : ?>
                    <a class="nav-link" href="<?= $urlManager->createUrl('user/index'); ?>">
                        <i class="fas fa-user-cog"></i>
                        <span>Users</span></a>
                <?php endif; ?>
                <?= Html::beginForm(['/site/logout'], 'post', ['class' => '']) ?>
                <?= Html::beginTag('button', ['class' => 'nav-link nav-menu-button', 'type' => 'submit']) ?>
                <i class="fas fa-sign-out-alt"></i>
                <span>Logout</span></a>
                <?= Html::endTag('button') ?>
                <?= Html::endForm() ?>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
    <?php endif; ?>

    <div id="content-wrapper" class="d-flex flex-column">
        <div id="content">
            <div class="container-fluid">
                <?php if($loggedIn) : ?>
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800"><?= Html::encode($this->title); ?></h1>
                        <!--<a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>-->
                    </div>
                <?php endif; ?>
                <?= $content ?>
            </div>
        </div>
        <footer class="sticky-footer bg-white">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>Copyright &copy; Your Website <?= date('Y'); ?></span>
                </div>
            </div>
        </footer>
    </div>
</div>

<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>