php/models/Notification.php
<?php

declare(strict_types=1);

namespace app\models;

use Yii;
use yii\db\ActiveQuery;
use app\exceptions\ValueError;

/**
 * This is the model class for table "notification".
 *
 * @property integer $id
 * @property string $text
 * @property string $creation_date
 * @property string $extra
 * @property integer $task_id
 * @property string $command
 * @property integer $type
 * @property integer $level
 * @property integer $taken_by_user_id
 * @property string $short_info
 *
 * @property Task $task
 */
class Notification extends \yii\db\ActiveRecord
{
    const LEVEL_UNKNOWN = 0;
    const LEVEL_LOW = 1;
    const LEVEL_MEDIUM = 2;
    const LEVEL_HIGH = 3;
    const LEVEL_CRITICAL = 4;

    const TYPE_UNKNOWN = 0;
    const TYPE_DOS = 1;
    const TYPE_CODE_EXECUTION = 2;
    const TYPE_OVERFLOW = 3;
    const TYPE_MEMORY_CORRUPTION = 4;
    const TYPE_SQL_INJECTION = 5;
    const TYPE_XSS = 6;
    const TYPE_DIRECTORY_TRAVERSAL = 7;
    const TYPE_RESPONSE_SPLITTING = 8;
    const TYPE_BYPASS = 9;
    const TYPE_GAIN_INFORMATION = 10;
    const TYPE_GAIN_PRIVILEGES = 11;
    const TYPE_CSRF = 12;
    const TYPE_FILE_INCLUSION = 13;

    public static function getLevelsAsArray() : array
    {
        return [
            'Unknown',
            'Low',
            'Medium',
            'High',
            'Critical',
        ];
    }

    public static function getTypesAsArray(): array
    {
        return [
            'DOS',
            'Code Execution',
            'Overflow',
            'Memory corruption',
            'SQL injection',
            'XSS',
            'Directory traversal',
            'Response splitting',
            'Bypass',
            'Gain information',
            'Gain privileges',
            'CSRF',
            'File inclusion',
        ];
    }


    /**
     * @inheritdoc
     */
    public static function tableName() : string
    {
        return 'notification';
    }

    /**
     * @inheritdoc
     */
    public function rules() : array
    {
        return [
            [['creation_date'], 'safe'],
            [['extra'], 'string'],
            [['task_id'], 'required'],
            [['task_id', 'type', 'level', 'taken_by_user_id'], 'integer'],
            [['short_info'], 'string', 'max' => 255],
            [['text'], 'string', 'max' => 4000],
            [['command'], 'string', 'max' => 512],
            [['task_id'], 'exist', 'skipOnError' => true, 'targetClass' => Task::className(), 'targetAttribute' => ['task_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() : array
    {
        return [
            'id' => 'ID',
            //'text' => 'текст уведомления',
            'text' => 'Text',
            'creation_date' => 'Creation Date',
            //'extra' => 'дополнительное поле для помещения кастомных данных, которые возможно понадобятся позже',
            'extra' => 'Extra data',
            //'task_id' => 'связь с задачей',
            'task_id' => 'Task',
            //'command' => 'Оригинальная команда, которая привела к выбросу уведомления',
            'command' => 'Original command',
            //'type' => 'тип уведомления (бага, RCE и прочее)',
            'type' => 'Type',
            //'level' => 'уровень уведомления (некритичный, критический и прочее)',
            'level' => 'Level',
            'taken_by_user_id' => 'Взят пользователем',
            //'short_info' => 'Краткая информация',
            'short_info' => 'Short info',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTask() : ActiveQuery
    {
        return $this->hasOne(Task::className(), ['id' => 'task_id']);
    }
    
    public function getErrorsAsString() : string
    {
        $string = '';
        $errors = $this->getErrors();
        foreach ($errors as $attributeName => &$attributeErrors) {
            $string .= "\nAttribute - '$attributeName':\n" . implode("\n", $attributeErrors);
        }
        return $string;
    }
    
    /**
     * Создано ли уведомление задачей администратора
     * @return bool
     */
    public function isCreatedByAdmin() : bool
    {
        return intval(Task::find()
            ->select(['user.id'])
            ->leftJoin('user', 'user.id = task.user_id')
            ->where(['task.id' => $this->task_id])->count()) === 1;       
    }

    public static function getLevelByValue(int $val): string
    {
        $levelMapping = [
            'unknown',
            'low',
            'medium',
            'high',
            'critical'
        ];
        if (!array_key_exists($val, $levelMapping)) {
            throw new ValueError('Unknown type');
        }
        return $levelMapping[$val];
    }
}

php/controllers/NotificationController.php
<?php

declare(strict_types=1);

namespace app\controllers;

use app\exceptions\ValueError;
use app\models\helpers\DemoRulesHelper;
use Yii;
use app\models\Notification;
use app\models\NotificationSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\auth\User;
use yii\filters\AccessControl;

/**
 * NotificationController implements the CRUD actions for Notification model.
 */
class NotificationController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors() : array
    {
        $availActions = ['index', 'view', ];
        $nonDemoActions = ['take', 'free', 'general'];
        $rulesHelper = new DemoRulesHelper($availActions, $nonDemoActions);
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => $rulesHelper->getAllActions(),
                'rules' => $rulesHelper->getRules(),
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    //'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Notification models.
     * @return mixed
     */
    public function actionIndex() : string
    {
        $searchModel = new NotificationSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Notification model.
     * @param integer $id
     * @return mixed
     */
    public function actionView(int $id) : string
    {
        $model = $this->findModel($id);
        $task = $model->getTask()->one();       
        $userId = User::getCurrentUserId();
        
        if ($model->taken_by_user_id !== $userId && $task->user_id !== $userId)
        {
            throw new ValueError('Can not get access to record');
        }
        
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Finds the Notification model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Notification the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel(int $id) : Notification
    {
        if (($model = Notification::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    /**
     * 
     * @param int $id
     * @return string
     * @throws \LogicException
     */
    public function actionTake(int $id) 
    {
        try
        {
            $model = $this->findModel($id);
            $user = User::getCurrentUser();
            
            //Если уже взято - редиректим
            if ($model->taken_by_user_id === $user->id)
            {
                return $this->redirect(['view', 'id' => $id]);
            }
            
            if ($user->isAdmin())
            {
                throw new \LogicException('User is admin');
            }
            if (!$model->isCreatedByAdmin())
            {
                throw new \LogicException('Motification is not created by admin task');
            }

            $model->taken_by_user_id = $user->id;
            if (!$model->validate())
            {
                throw new \LogicException('Model->validate() error');
            } 
            $model->save();
            return $this->redirect(['view', 'id' => $id]);
        } catch (\Exception $ex) {
            \Yii::error(__METHOD__.": ".$ex->getMessage());
            return $this->redirect(['general']);
        }          
    }
    
    /**
     * 
     * @param integer $id
     * @return type
     */
    public function actionFree(int $id)
    {
        try
        {
            $user = User::getCurrentUser();
            if ($user->isAdmin())
            {
                throw new \LogicException('User is admin');
            }
            
            $model = $this->findModel($id);
            if ($model->taken_by_user_id !== User::getCurrentUserId())
            {
                return $this->redirect(['index']);
            }
            
            $model->taken_by_user_id = null;
            $model->save();
                    
        } catch (\Exception $ex) {
            \Yii::error(__METHOD__.": ".$ex->getMessage());
        }
        return $this->redirect(['general']);
    }
    
    /**
     * Страница уведомлений, которые были созданы от задач администраторов
     * @return string
     */
    public function actionGeneral() : string
    {
        $searchModel = new NotificationSearch();
        $dataProvider = $searchModel->searchCreatedByAdmin(Yii::$app->request->queryParams);

        return $this->render('general', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
}

php/controllers/TaskController.php
<?php

declare(strict_types=1);

namespace app\controllers;

use app\exceptions\ValueError;
use app\models\helpers\DemoRulesHelper;
use app\models\Notification;
use app\models\NotificationSearch;
use app\widgets\card\Card;
use app\widgets\progressbar\ProgressBar;
use Yii;
use app\models\Task;
use app\models\TaskSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use app\models\auth\User;
use yii\filters\AccessControl;
use yii\web\UploadedFile;
use app\widgets\charts\DonutDataset;
use app\widgets\charts\DonutChart;
use app\models\helpers\PieChartOptionsBuilder;

/**
 * TaskController implements the CRUD actions for Task model.
 */
class TaskController extends BaseController
{
    /**
     *
     * @var string 
     */
    protected static $nonAdminMesage = 'текущий пользователь не является администратором';

    /**
     * @inheritdoc
     */
    public function behaviors() : array
    {
        $availActions = ['index', 'view', ];
        $nonDemoActions = ['create', 'update', 'approve', 'push',];
        $rulesHelper = new DemoRulesHelper($availActions, $nonDemoActions);
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => $rulesHelper->getAllActions(),
                'rules' => $rulesHelper->getRules(),
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    //'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Task models.
     * @return mixed
     */
    public function actionIndex() : string
    {
        $searchModel = new TaskSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Task model.
     * @param integer $id
     * @return mixed
     */
    public function actionView(int $id) : string
    {
        $model = $this->findModel($id);
        $chart = new DonutChart();
        $chart->setHeader('Notifications by type');
        $nSearch = new NotificationSearch();
        $nData = $nSearch->getNotificationsCount([$model->id], ['level'], false);
        $colors = $this->getDonutColorsByNotificationLevel($nData);
        $chart->setLabels(array_keys($nData));
        $chart->setOptionsBuilder(new PieChartOptionsBuilder());
        $chart->updateDatasets([
            (new DonutDataset())
                ->setData(array_values($nData))
                ->setBackgroundColors($colors)
                ->setHoverBackground($colors)

        ]);
        $cardProgress = new Card();
        //todo: move to controller, get info from db
        $cardProgress->cardType = Card::TYPE_INFO;
        $cardProgress->header = 'Task progress';
        $cardProgress->text = '36%';
        $cardProgress->progressBar = new ProgressBar();
        $cardProgress->progressBar->type = ProgressBar::TYPE_INFO;
        $cardProgress->progressBar->value = 36;
        return $this->render('view', [
            'model' => $model,
            'domains' => $model->readDomains(),
            'domainsCount' => 0,
            'chart' => $chart,
            'cardProgress' => $cardProgress,
        ]);
    }

    /**
     * Возврат набора цветов для найденных уведомлений
     * @param array $nData
     * @return array
     */
    private function getDonutColorsByNotificationLevel(array $nData): array
    {
        $result = [];
        $colors = [
            DonutDataset::COLOR_NOTIFICATION_UNKNOWN,
            DonutDataset::COLOR_NOTIFICATION_LOW,
            DonutDataset::COLOR_NOTIFICATION_MEDIUM,
            DonutDataset::COLOR_NOTIFICATION_HIGH,
            DonutDataset::COLOR_NOTIFICATION_CRITICAL
        ];
        $nLevels = Notification::getLevelsAsArray();
        for ($i = 0; $i < count($nLevels); $i++) {
            if (array_key_exists($nLevels[$i], $nData)) {
                $result[] = $colors[$i];
            }
        }
        return $result;
    }

    /**
     * Creates a new Task model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     * @throws \Exception
     */
    public function actionCreate()
    {
        $model = new Task();

        if ($model->load(Yii::$app->request->post())) {
            $model->status = Task::STATUS_CREATED;
            $tmpDomainsFile = UploadedFile::getInstance($model, 'domains');
            if ($tmpDomainsFile !== null) {
                $model->filename = $model->uploadFile($tmpDomainsFile);
            }
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                //'domains' => $model->readDomains(),
            ]);
        }
    }

    /**
     *
     * @param int $id
     * @return mixed
     * @throws \Exception
     */
    public function actionApprove(int $id)
    {
        if (!User::currentUserIsAdmin())
        {
            \Yii::error(__METHOD__.": ".self::$nonAdminMesage);
            return $this->redirect(['view', 'id' => $id]);
        }
        Task::updateAll(['status' => Task::STATUS_APPROVED], ['=', 'id', $id]);
        return $this->redirect(['view', 'id' => $id]);
    }
    
    /**
     * 
     * @param integer $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionPush(int $id) : string
    {
        $model = $this->findModel($id);
        if (!User::currentUserIsAdmin())
        {
            \Yii::error(__METHOD__.": ".self::$nonAdminMesage);
            return $this->redirect(['view', 'id' => $model->id]);
        }
        
        if ($model->status !== Task::STATUS_APPROVED)
        {
            throw new ValueError('Task must be in "approved" status');
        }
        if (!$model)
        {
            throw new NotFoundHttpException('Not found task with id '.$id);
        }
        
        $domainsCount = $model->pushToQueue('task');
        return $this->render('view', [
            'model' => $model,
            'domains' => $model->readDomains(),
            'domainsCount' => $domainsCount,
        ]);      
    }

    /**
     * Finds the Task model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Task the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel(int $id) : Task
    {
        if (($model = Task::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

php/views/notification/general.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\models\auth\User;

/* @var $this yii\web\View */
/* @var $searchModel app\models\NotificationSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Notifications';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="notification-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Notification', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'short_info',
            'creation_date',
            'type',
            'level',
            [
                'class' => 'yii\grid\ActionColumn',
                'buttons' => [
                    'take' => function ($url, $model, $key) {
                        if ($model->taken_by_user_id === User::getCurrentUserId())
                        {
                            return '';
                        }
                        
                        $data = [
                            'notification/take', 
                            'id' => $model->id,
                            ];
                        $icon = 'fa-file-import';
                        return Html::a ( '<span class="fa '.$icon.'" aria-hidden="true"></span> ', $data);
                    },
                ],
                'template' => '{take} {free}', 
            ],
        ],
    ]); ?>
</div>

php/views/notification/index.php
<?php

declare(strict_types=1);

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use app\models\auth\User;
use app\models\helpers\FieldHelper;
use app\models\Notification;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $searchModel app\models\NotificationSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Notifications';
$this->params['breadcrumbs'][] = $this->title;
$n = new Notification();
$levelValues = FieldHelper::getFieldValues($n, 'level');
$typeValues = FieldHelper::getFieldValues($n, 'type');
?>
<div class="notification-index">
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'attribute' => 'short_info',
                'enableSorting' => false,
            ],
            [
                'attribute' => 'creation_date',
                'filter' =>   DatePicker::widget([
                    'name' => 'NotificationSearch[creation_date]',
                    'value' => $searchModel->creation_date,
                    'pluginOptions' => [
                        'format' => 'yyyy-mm-dd',
                        'todayHighlight' => true
                    ],
                    'convertFormat' => false,
                ]),
            ],
            [
                'attribute' => 'type',
                'format' => 'raw',
                'filter' => $typeValues,
                'value' => function ($model) {
                    return FieldHelper::beautify(FieldHelper::getTypeString($model, 'type', $model->type));
                },
            ],
            [
                'attribute' => 'level',
                'format' => 'raw',
                'filter' => $levelValues,
                'value' => function ($model) {
                    return FieldHelper::beautify(FieldHelper::getTypeString($model, 'level', $model->level));
                },
            ],
            [
                'attribute' => 'task_name_like',
                'label' => 'Task name',
                'format' => 'raw',
                'filter' => Html::textInput(
                        'NotificationSearch[task_name_like]',
                        $searchModel->task_name_like,
                        ['class' => 'form-control']
                ),
                'value' => function ($model) {
                    $task = $model->getTask()->one();
                    return Html::a(
                        Html::encode($task->name),
                        Url::to(['task/view', 'id' => $task->id])
                    );
                },
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'buttons' => [
                    'free' => function ($url, $model, $key) {
                        if ($model->taken_by_user_id !== User::getCurrentUserId())
                        {
                            return '';
                        }                       
                        $data = [
                            'notification/free', 
                            'id' => $model->id,
                            ];
                        $icon = 'fa-file-export';
                        return Html::a ( '<span class="fa '.$icon.'" aria-hidden="true"></span> ', $data);
                    },
                ],
                'template' => '{view} {free}'
            ],
            
        ],
    ]); ?>
</div>

php/views/notification/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use app\models\auth\User;

/* @var $this yii\web\View */
/* @var $model app\models\Notification */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Notifications', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="notification-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?php
            if ($model->taken_by_user_id === User::getCurrentUserId() && Yii::$app->params['isDemo'] === 0)
            {
                echo Html::a(
                        'Free', [
                        'free', 'id' => $model->id], 
                        ['class' => 'btn btn-primary']
                    );
            }
        ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'text',
            'creation_date',
            'extra:ntext',
            'command',
            'type',
            'level',
        ],
    ]) ?>

</div>